### ISSUE TITLE
[Feature Request] add flags to messages

### ISSUE THREAD

**Issue by therealguy90** [p4535992/foundryvtt-chat-media#2]
It'd be great for this module to add content to the `flags` field of the ChatMessage containing filepaths or links for each media included in the message. The content is being uploaded to the server, but it doesn't have the same filename as the original file that was uploaded. This would allow for better interaction with other modules, or use a macro to grab the link/path of the image to put into a journal.

**Comment by p4535992** [comment]
done on 3.3.5
