### ISSUE TITLE
v12

### ISSUE THREAD

**Issue by brunocalado** [p4535992/foundryvtt-chat-media#3]
Hi. Can you update this module to v12? Thank you!

**Comment by p4535992** [comment]
The manifest for 3.3.6 is updated. Maybe there is a bug ?

**Comment by brunocalado** [comment]
> The manifest for 3.3.6 is updated. Maybe there is a bug ?

![image](https://github.com/p4535992/foundryvtt-chat-media/assets/4999783/69c4a07c-5487-48e5-b739-36873e64a031)

**Comment by brunocalado** [comment]
Maybe you need to change:
    "compatibility": {
        "minimum": 11,
        "verified": 11,
        "maximum": 12
    },
    
    Or the foundry package page

**Comment by brunocalado** [comment]
> "verified": 11,

I think so. So, just change "verified": 11, to "verified": 12

**Comment by p4535992** [comment]
**i can but i do not want it, i didn't test on v12 yet** . However, if you can give me confirmation that you have not found any functionality problems in a v12 I will sec the parameter  without any problems.

**Comment by brunocalado** [comment]
> **i can but i do not want it, i didn't test on v12 yet** . However, if you can give me confirmation that you have not found any functionality problems in a v12 I will set the parameter without any problems.

It's working well. But, I didn't test with all players.

**Comment by p4535992** [comment]
it's enough for me. i will update the manifest tonight

**Comment by brunocalado** [comment]
> it's enough for me. i will update the manifest tonight

Hi! Any news on this? 
![image](https://github.com/p4535992/foundryvtt-chat-media/assets/4999783/53b4d26f-5078-4f65-a041-39fd0f13fff4)

**Comment by Chromie192** [comment]
Is this abandoned?

**Comment by p4535992** [comment]
I just updated the module json, but it should be working.

**Comment by Chromie192** [comment]
> I just updated the module json, but it should be working.

Awesome! Seems to be working normally on v12 again!
